---
kind: pipeline
type: docker
name: default

steps:

- name: createimage
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - ls -l ./
  - ls -l /var/run/
  - docker build -t kicad .
  - chmod -R o+rw ./

- name: pcbdraw
  image: kicad
  pull: if-not-exists
  commands:
  - pcbdraw breadbee.kicad_pcb breadbee.png

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

...
